# Generated by Django 5.0.4 on 2024-04-19 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='column_id',
            new_name='column',
        ),
    ]
